package com.aerodynamic.aerodynamic.pricing_engine.service.impl;

import com.aerodynamic.aerodynamic.pricing_engine.dto.PricingRuleRequest;
import com.aerodynamic.aerodynamic.pricing_engine.dto.PricingRuleResponse;
import com.aerodynamic.aerodynamic.pricing_engine.model.PricingRule;
import com.aerodynamic.aerodynamic.pricing_engine.model.User;
import com.aerodynamic.aerodynamic.pricing_engine.model.enums.StatusRule;
import com.aerodynamic.aerodynamic.pricing_engine.repository.PricingRuleRepository;
import com.aerodynamic.aerodynamic.pricing_engine.repository.UserRepository;
import com.aerodynamic.aerodynamic.pricing_engine.service.PricingRuleService;

import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class PricingRuleServiceImpl implements PricingRuleService {

    private final PricingRuleRepository pricingRuleRepository;
    private final UserRepository userRepository;

    // Constructor injection (Best practice in Spring Boot)
    public PricingRuleServiceImpl(PricingRuleRepository pricingRuleRepository, UserRepository userRepository) {
        this.pricingRuleRepository = pricingRuleRepository;
        this.userRepository = userRepository;
    }

    /**
     * Creates a new pricing rule from the request DTO data.
     * The ID is auto-generated by the database, so it is omitted from the request.
     */
    @Override
    public PricingRuleResponse createPricingRule(PricingRuleRequest request) {
        // 1. Find the creator user in the database using the ID from the request
        User creatorUser = userRepository.findById(request.getCreatorUserId())
                .orElseThrow(() -> new RuntimeException("User not found with id: " + request.getCreatorUserId()));

        // 2. Map from the Request DTO to the JPA Entity (PricingRule)
        PricingRule rule = new PricingRule();
        rule.setRuleName(request.getRuleName());
        rule.setBussinessVariable(request.getBussinessVariable());
        rule.setCondition(request.getConditionOperator());
        rule.setConditionValue(request.getConditionValue());
        rule.setAdjustmentType(request.getAdjustmentType());
        rule.setAdjustmentValue(request.getAdjustmentValue());
        rule.setStatus(StatusRule.ACTIVE); // ← cambio aquí: antes request.getStatus()
        rule.setCreatorUser(creatorUser);

        // 3. Save to the database using the repository (ID will be generated automatically)
        PricingRule savedRule = pricingRuleRepository.save(rule);

        // 4. Convert the saved entity to a Response DTO and return it
        return mapToResponse(savedRule);
    }

    /**
     * Retrieves all registered pricing rules and converts them to Response DTOs.
     */
    @Override
    public List<PricingRuleResponse> getAllPricingRules() {
        return pricingRuleRepository.findAll().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    /**
     * Searches for rules filtered by their status (using the repository custom method).
     */
    @Override
    public List<PricingRuleResponse> getPricingRulesByStatus(StatusRule status) {
        return pricingRuleRepository.findByStatus(status).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    /**
     * Private helper method to centralize the Entity -> Response DTO conversion.
     */
    private PricingRuleResponse mapToResponse(PricingRule rule) {
        return new PricingRuleResponse(
                rule.getIdRule(),
                rule.getRuleName(),
                rule.getBussinessVariable(),
                rule.getConditionOperator(),
                rule.getConditionValue(),
                rule.getAdjustmentType(),
                rule.getAdjustmentValue(),
                rule.getStatus(),
                rule.getCreatorUser() != null ? rule.getCreatorUser().getId() : null
        );
    }
}
