spring.application.name=aerodynamic.pricing-engine 
# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/pricing_engine
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA / Hibernate
# 'update' creará o actualizará las tablas automáticamente según tus entidades de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect